key: "value"

# params.yaml

TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 500
  per_device_train_batch_size: 8
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps 
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_steps: 16
  learning_rate: 5e-5

DataTransformation:
  max_input_length: 512
  max_target_length: 128


